services:
  chat_app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_INNER_PORT}"
      - "${APP_GRPC_PORT}:${APP_GRPC_INNER_PORT}"
    depends_on:
      - chat_db
    networks:
      - micro-proxy-net

  chat_db:
    image: postgres:15.3
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - micro-proxy-net

networks:
  micro-proxy-net:
    external: true
    name: chaotic-network